name: 增加企鹅读书时长

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 1-8 * * *'
  watch:
    types: started
  repository_dispatch:
    types: start
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/XQ0120/PlayerActions.git ~/PlayerActions
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/PlayerActions
          git checkout master
          npm install
      - name: '运行 【增加QQ阅读时长】'
        run: |
          cd ~/PlayerActions/workflow/LocalCookie
          node AddQQReadTime.js
        env:
          TZ: Asia/shanghai
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
